name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Cambia a la rama donde tengas tu index.html si no es main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # ./ si tu index.html está en la raíz del repositorio
